import type { ProviderWithOperationsCount } from "./provider.types"

export const providersMock: ProviderWithOperationsCount[] = [
  {
    id: 1,
    name: "Bryan Martins",
    phone: "(11) 99874-1123",
    notes: "Negociações frequentes.",
    defaultInterestRate: 4.5,
    defaultCompensationDays: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 23,
  },
  {
    id: 2,
    name: "Valentina Macedo",
    phone: "(11) 99123-4455",
    notes: null,
    defaultInterestRate: 3,
    defaultCompensationDays: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 8,
  },
  {
    id: 3,
    name: "Lara Oliveira",
    phone: "(19) 99888-2200",
    notes: "Pagamento sempre antecipado.",
    defaultInterestRate: 3.5,
    defaultCompensationDays: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 15,
  },
  {
    id: 4,
    name: "Gabriel Costa",
    phone: "(31) 99777-1212",
    notes: null,
    defaultInterestRate: 4,
    defaultCompensationDays: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 2,
  },
  {
    id: 5,
    name: "Isabela Ferreira",
    phone: "(41) 99654-3344",
    notes: "Prefere contato por WhatsApp.",
    defaultInterestRate: 4.5,
    defaultCompensationDays: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 31,
  },
  {
    id: 6,
    name: "Lucas Almeida",
    phone: "(21) 98888-1000",
    notes: null,
    defaultInterestRate: 2.8,
    defaultCompensationDays: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 12,
  },
  {
    id: 7,
    name: "Amanda Ribeiro",
    phone: "(62) 99999-8877",
    notes: "Taxa negociada recentemente.",
    defaultInterestRate: 5,
    defaultCompensationDays: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 5,
  },
  {
    id: 8,
    name: "Pedro Henrique",
    phone: "(85) 99712-4411",
    notes: null,
    defaultInterestRate: 3.8,
    defaultCompensationDays: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 19,
  },
  {
    id: 9,
    name: "Juliana Souza",
    phone: "(71) 99555-7878",
    notes: "Cliente antigo.",
    defaultInterestRate: 3.2,
    defaultCompensationDays: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 41,
  },
  {
    id: 10,
    name: "Rafael Gomes",
    phone: "(48) 99111-9090",
    notes: null,
    defaultInterestRate: 4.2,
    defaultCompensationDays: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    operationsCount: 14,
  },
]