/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PageRouteImport } from './app/page'
import { Route as AuthLayoutRouteImport } from './app/_auth/layout'
import { Route as AuthChequesPageRouteImport } from './app/_auth/cheques/page'
import { Route as AuthClientesPageRouteImport } from './app/_auth/clientes/page'
import { Route as AuthClientesNovoRouteImport } from './app/_auth/clientes/novo'
import { Route as AuthDashboardPageRouteImport } from './app/_auth/dashboard/page'
import { Route as AuthOperacoesNovaRouteImport } from './app/_auth/operacoes/nova'
import { Route as AuthClientesIdEditarRouteImport } from './app/_auth/clientes/$id/editar'
import { Route as AuthOperacoesIdPageRouteImport } from './app/_auth/operacoes/$id/page'

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChequesPageRoute = AuthChequesPageRouteImport.update({
  id: '/cheques/',
  path: '/cheques/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthClientesPageRoute = AuthClientesPageRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthClientesNovoRoute = AuthClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthDashboardPageRoute = AuthDashboardPageRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthOperacoesNovaRoute = AuthOperacoesNovaRouteImport.update({
  id: '/operacoes/nova',
  path: '/operacoes/nova',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthClientesIdEditarRoute = AuthClientesIdEditarRouteImport.update({
  id: '/clientes/$id/editar',
  path: '/clientes/$id/editar',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthOperacoesIdPageRoute = AuthOperacoesIdPageRouteImport.update({
  id: '/operacoes/$id/',
  path: '/operacoes/$id/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/clientes/novo': typeof AuthClientesNovoRoute
  '/operacoes/nova': typeof AuthOperacoesNovaRoute
  '/cheques/': typeof AuthChequesPageRoute
  '/clientes/': typeof AuthClientesPageRoute
  '/dashboard/': typeof AuthDashboardPageRoute
  '/clientes/$id/editar': typeof AuthClientesIdEditarRoute
  '/operacoes/$id/': typeof AuthOperacoesIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/clientes/novo': typeof AuthClientesNovoRoute
  '/operacoes/nova': typeof AuthOperacoesNovaRoute
  '/cheques': typeof AuthChequesPageRoute
  '/clientes': typeof AuthClientesPageRoute
  '/dashboard': typeof AuthDashboardPageRoute
  '/clientes/$id/editar': typeof AuthClientesIdEditarRoute
  '/operacoes/$id': typeof AuthOperacoesIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_auth/clientes/novo': typeof AuthClientesNovoRoute
  '/_auth/operacoes/nova': typeof AuthOperacoesNovaRoute
  '/_auth/cheques/': typeof AuthChequesPageRoute
  '/_auth/clientes/': typeof AuthClientesPageRoute
  '/_auth/dashboard/': typeof AuthDashboardPageRoute
  '/_auth/clientes/$id/editar': typeof AuthClientesIdEditarRoute
  '/_auth/operacoes/$id/': typeof AuthOperacoesIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes/novo'
    | '/operacoes/nova'
    | '/cheques/'
    | '/clientes/'
    | '/dashboard/'
    | '/clientes/$id/editar'
    | '/operacoes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes/novo'
    | '/operacoes/nova'
    | '/cheques'
    | '/clientes'
    | '/dashboard'
    | '/clientes/$id/editar'
    | '/operacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/clientes/novo'
    | '/_auth/operacoes/nova'
    | '/_auth/cheques/'
    | '/_auth/clientes/'
    | '/_auth/dashboard/'
    | '/_auth/clientes/$id/editar'
    | '/_auth/operacoes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/cheques/': {
      id: '/_auth/cheques/'
      path: '/cheques'
      fullPath: '/cheques/'
      preLoaderRoute: typeof AuthChequesPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/clientes/': {
      id: '/_auth/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthClientesPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/clientes/novo': {
      id: '/_auth/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthClientesNovoRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/operacoes/nova': {
      id: '/_auth/operacoes/nova'
      path: '/operacoes/nova'
      fullPath: '/operacoes/nova'
      preLoaderRoute: typeof AuthOperacoesNovaRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/clientes/$id/editar': {
      id: '/_auth/clientes/$id/editar'
      path: '/clientes/$id/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AuthClientesIdEditarRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/operacoes/$id/': {
      id: '/_auth/operacoes/$id/'
      path: '/operacoes/$id'
      fullPath: '/operacoes/$id/'
      preLoaderRoute: typeof AuthOperacoesIdPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthClientesNovoRoute: typeof AuthClientesNovoRoute
  AuthOperacoesNovaRoute: typeof AuthOperacoesNovaRoute
  AuthChequesPageRoute: typeof AuthChequesPageRoute
  AuthClientesPageRoute: typeof AuthClientesPageRoute
  AuthDashboardPageRoute: typeof AuthDashboardPageRoute
  AuthClientesIdEditarRoute: typeof AuthClientesIdEditarRoute
  AuthOperacoesIdPageRoute: typeof AuthOperacoesIdPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthClientesNovoRoute: AuthClientesNovoRoute,
  AuthOperacoesNovaRoute: AuthOperacoesNovaRoute,
  AuthChequesPageRoute: AuthChequesPageRoute,
  AuthClientesPageRoute: AuthClientesPageRoute,
  AuthDashboardPageRoute: AuthDashboardPageRoute,
  AuthClientesIdEditarRoute: AuthClientesIdEditarRoute,
  AuthOperacoesIdPageRoute: AuthOperacoesIdPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
